language: cpp

compiler:
 - clang
 - gcc

branches:
  only:
    - master

before_install:
  - echo "yes" | sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
  - echo "yes" | sudo apt-add-repository 'deb http://repos.codelite.org/wx3.0/ubuntu/ precise universe'
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update
  - sudo apt-get install libwxgtk3.0-dev libopenal-dev freeglut3-dev libglew-dev
  - sudo apt-get install aria2 -qq
  - download_extract() { aria2c -x 16 $1 -o $2 && tar -xf $2; }
# Travis uses CMake 2.8.7. We require 2.8.8. Grab latest
  - sudo apt-get install -qq g++-4.8
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
  - sudo apt-get install lib32stdc++6 -qq &&
    aria2c -x 16 http://www.cmake.org/files/v2.8/cmake-2.8.12.1-Linux-i386.sh &&
    chmod a+x cmake-2.8.12.1-Linux-i386.sh &&
    sudo ./cmake-2.8.12.1-Linux-i386.sh --skip-license --prefix=/usr;

before_script:
 - git submodule update --init --recursive
 - mkdir build
 - cd build
 - cmake ..

script:
 - make 

